model:
  arch: minigpt_3d
  model_type: pretrain
  max_txt_len: 1024
  end_sym: "###"
  llama_model: "./params_weight/Phi_2"
  ckpt: './output/test/stage_2/checkpoint_0.pth'
  use_grad_checkpoint: True
  chat_template: True
  lora_r: 64
  lora_alpha: 16
  only_train_pc_linear: False
  pc_linear_layer: 2
  use_MQE: False  #  False: not use  query expert
  query_expert_router_type: 'Sparse Router'  # three types： Constant Router, Sparse Router,  Soft Router
  query_expert_num: 8
  query_expert_top_k: 2  #  the top_k numbers of  query expert in 'Sparse Router'
  QFormer_lora_r: 8   # 0 : not use QFormer lora
  QFormer_lora_alpha: 16
  train_QFormer_norm: True
  QFormer_lora_module: ["query", "key",  "value"]

datasets:
  Objaverse_detailed:
    batch_size: 6       #  4
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 2   # 3

  Objaverse_single_round:
    batch_size: 10      # 4
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 3     # 8

  Objaverse_mutil_round:
    batch_size: 4
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 3

 

 

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"

  init_lr: 1e-5
  min_lr: 1e-6
  warmup_lr: 1e-6

  weight_decay: 0.05
  num_workers: 12

  max_epoch: 3
  warmup_steps: 3000
  iters_per_epoch: 10000

  seed: 42
  output_dir: "./output/test/stage_3"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: True
  job_name: minigpt3d_finetune
