model:
  arch: minigpt_3d
  model_type: pretrain
  max_txt_len: 1024
  end_sym: "###"
  llama_model: "./params_weight/Phi_2"
  ckpt: './params_weight/TinyGPT_V_stage_3/TinyGPT-V_for_Stage3.pth'
  use_grad_checkpoint: True
  chat_template: True
  lora_r: 64
  lora_alpha: 16
  only_train_pc_linear: True
  pc_linear_layer: 2
  use_MQE: False  #  False: not use  query expert
  QFormer_lora_r: 0   # 0 : not use QFormer lora


datasets:
  Objaverse_brief:
    batch_size: 9   # 9
    text_processor:
      train:
        name: "blip_caption"


run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"

  init_lr: 3e-5
  min_lr: 1e-5
  warmup_lr: 1e-6

  weight_decay: 0.05
  num_workers: 12

  max_epoch: 1
  warmup_steps: 7000
  iters_per_epoch: 70000


  seed: 42
  output_dir: "./output/test/stage_1"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: True
  job_name: minigpt3d_finetune
