datasets:
  Objaverse_brief:
    data_type: point_cloud
    build_info:

      data_path: ./data/objaverse_data
      ann_path: ./data/anno_data/PointLLM_brief_description_660K_filtered.json
      pointnum: 8192
      conversation_types: "simple_description"  # * default is simple_des, used for stage1 pre-train
      use_color: True